trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Listing contents of the repository..."
    ls -la $(Build.SourcesDirectory)
  displayName: 'List Repo Directory'


- script: |
    echo "Pulling Docker image: carbonetes/broker"
    docker pull carbonetes/broker
    echo "Saving image to broker.tar"
    docker save carbonetes/broker -o broker.tar
  displayName: 'Pull and Save Docker Image'

- script: |
    echo "Listing generated tar file..."
    ls -lh broker.tar
  displayName: 'List Tar File'


- task: Jacked@1
  inputs:
    token: 'cn_VLNgDRcCTMbRMeW84J7en2Y2'
    scanType: 'filesystem'
    scanName: '$(Build.SourcesDirectory)'
    failCriteria: 'medium'
    skipBuildFail: 'false'


- task: Jacked@1
  inputs:
    token: 'cn_VLNgDRcCTMbRMeW84J7en2Y2'
    scanType: 'tarball'
    scanName: '$(Build.SourcesDirectory)'
    failCriteria: 'medium'
    skipBuildFail: 'false'

- task: Jacked@1
  inputs:
    token: 'cn_VLNgDRcCTMbRMeW84J7en2Y2'
    scanType: 'image'
    scanName: 'carbonetes/broker'
    failCriteria: 'medium'
    skipBuildFail: 'false'


- task: Diggity@1
  inputs:
    token: 'cn_VLNgDRcCTMbRMeW84J7en2Y2'
    scanType: 'image'
    scanName: 'carbonetes/broker'
    failCriteria: 'medium'
    skipBuildFail: 'false'

- task: Diggity@1
  inputs:
    token: 'cn_VLNgDRcCTMbRMeW84J7en2Y2'
    scanType: 'tarball'
    scanName: 'broker.tar'
    failCriteria: 'medium'
    skipBuildFail: 'false'


- task: Diggity@1
  inputs:
    token: 'cn_VLNgDRcCTMbRMeW84J7en2Y2'
    scanType: 'filesystem'
    scanName: '$(Build.SourcesDirectory)'
    failCriteria: 'medium'
    skipBuildFail: 'false'